### ISSUE TITLE
Flask style test failing health check in CI

### ISSUE THREAD

**Issue by jab** [pre-commit/pre-commit#1575]
Flask's style test in GitHub actions runs `tox -e style`, which runs `pre-commit run --all-files --show-diff-on-failure`, which is failing with "An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment".

Note, this does not reproduce locally.

AFAIK, this first appeared in pallets/flask#3739.

We're trying to debug this over in pallets/flask#3740 where I've temporarily added a `cat .../pre-commit.log` command. Output here: https://github.com/pallets/flask/pull/3740/checks?check_run_id=1018335736#step:9:14

Neither the error message nor the log actually say what specifically about the environment is unhealthy.
 
Any ideas?

Thanks!

**Comment by asottile** [comment]
thanks for the report, this has been fixed in 2.7.1

**Comment by jab** [comment]
Thanks for the quick fix! And thanks for reporting the issue with the cache key. I've repurposed pallets/flask#3740 to fix that.

From #1576, it looks like the error message emitted when an unhealthy environment is found still does not include what specifically was found to be unhealthy about it, which makes it hard to know what the problem is. Would it make sense to include that info in the error message?

**Comment by asottile** [comment]
there isn't any information available at that point, healthy is a yes/no sort of thing

**Comment by jab** [comment]
Sure, but that could be changed if you wanted to make the error message more useful / actionable.

e.g. Instead of returning a boolean where `False` doesn't tell you which specific health check failed, you could return a namedtuple or something, with a `healthy` boolean in it, but also the results of each check, which could be included in the error message. Health check errors shown by e.g. Hypothesis, the Flask [Healthcheck extension](https://github.com/runscope/healthcheck), etc. do this, and it's way more usable.

**Comment by asottile** [comment]
I'm sorry but no, it's never supposed to happen, this was a bug.
