### ISSUE TITLE
No module named pre_commit

### ISSUE THREAD

**Issue by Eason0210** [pre-commit/pre-commit#2153]
After updating to latest version, I got an error "No module named pre_commit"  when git commit:
Does anyone know how to fix it?

```bash
.nixpkgs
❯ pre-commit --version
pre-commit 2.16.0

.nixpkgs on  master
❯ pre-commit install
pre-commit installed at .git/hooks/pre-commit

.nixpkgs on  master
❯ pre-commit run --all-files
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
black....................................................................Passed

.nixpkgs on  master
❯ git commit -m "Enable builtin pixel scrolling in Emacs 29"
/nix/store/x0fw0l4d6zwgfdwbpp23iwhm3c6a1hh3-python3-3.9.6/bin/python3.9: No module named pre_commit
```

I install pre-commit with nix on  macOS.

This is my [nix-config ](https://github.com/Eason0210/system/blob/3d8adaf3a29b60808664ad38102aeac255edf800/modules/home-manager/default.nix#L93)  and [.pre-commit-config.yaml](https://github.com/Eason0210/system/blob/master/.pre-commit-config.yaml)

Fix it:  I try to install pre-commit by python module, and it works now.

**Comment by Eason0210** [comment]
Fix it by install pre-commit by python module, and it works now.

**Comment by asottile** [comment]
sounds like a bug in the nix packaging -- since that works fine elsewhere

**Comment by felschr** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/148353.

**Comment by asottile** [comment]
that patch is not really correct but I guess that's nix's problem and not mine

**Comment by davidmpaz** [comment]
Just in case someone stumble upon this. For me the solution during development was that I needed to install git hooks again in project.

After making myself sure that I was using the proper binaries. I was still having this issue until I ran: `pre-commit install` again
