### ISSUE TITLE
"pre-commit-hooks.yaml does not exist"

### ISSUE THREAD

**Issue by lrcarvalho** [pre-commit/pre-commit#577]
Hi guys, 

After the last release (0.16.0) we started to facing some issues. The message is: 
```
Updating https://github.com/hootsuite/pre-commit-php.git...[INFO] Initializing environment for https://github.com/hootsuite/pre-commit-php.git. 
[INFO] Initializing environment for https://github.com/hootsuite/pre-commit-php.git. 
An error has occurred: InvalidManifestError: 
=====> /home/rof/.pre-commit/repoB1V3Py/.pre-commit-hooks.yaml does not exist 
Check the log at ~/.pre-commit/pre-commit.log"
```
After force to back to the last version (0.15.4), no more errors found. 

Can you give a look on this error?

Thanks!

**Comment by asottile** [comment]
This is an [intentional change](https://github.com/pre-commit/pre-commit/blob/master/CHANGELOG.md#0160) in 0.16.0 -- it removed backward compatibility which has been issuing a warning for over 6 months.

The specific repository in question is [no longer maintained](https://github.com/hootsuite/pre-commit-php/issues/16) (see also [here](https://github.com/hootsuite/pre-commit-php/issues/22)) and you should consider using the [maintained fork](https://github.com/digitalpulp/pre-commit-php).  The maintained fork does not have this problem :)

**Comment by asottile** [comment]
For others getting the same error message, `pre-commit autoupdate` is the usual blanket fix (assuming the upstream repositories are fixed)

**Comment by asottile** [comment]
Going to close this as it was intentional

**Comment by khru** [comment]
This issue it's happening to me too,

```
[INFO] Initializing environment for https://github.com/hootsuite/pre-commit-php.git.
An error has occurred: InvalidManifestError:
=====> /home/evalverde/.cache/pre-commit/repoTO4tFY/.pre-commit-hooks.yaml does not exist
Check the log at /home/evalverde/.cache/pre-commit/pre-commit.log
```

```
An error has occurred: InvalidManifestError: 
=====> /home/evalverde/.cache/pre-commit/repoTO4tFY/.pre-commit-hooks.yaml does not exist
Traceback (most recent call last):
  File "/home/evalverde/.local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/home/evalverde/.local/lib/python2.7/site-packages/pre_commit/main.py", line 291, in main
    return run(args.config, store, args)
  File "/home/evalverde/.local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 253, in run
    for hook in all_hooks(config, store)
  File "/home/evalverde/.local/lib/python2.7/site-packages/pre_commit/repository.py", line 221, in all_hooks
    for repo in root_config['repos']
  File "/home/evalverde/.local/lib/python2.7/site-packages/pre_commit/repository.py", line 222, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/evalverde/.local/lib/python2.7/site-packages/pre_commit/repository.py", line 197, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/evalverde/.local/lib/python2.7/site-packages/pre_commit/repository.py", line 167, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "/home/evalverde/.local/lib/python2.7/site-packages/cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/evalverde/.local/lib/python2.7/site-packages/cfgv.py", line 49, in reraise_as
    six.reraise(tp, tp(e), tb)
  File "/home/evalverde/.local/lib/python2.7/site-packages/cfgv.py", line 46, in reraise_as
    yield
  File "/home/evalverde/.local/lib/python2.7/site-packages/cfgv.py", line 396, in load_from_filename
    raise ValidationError('{} does not exist'.format(filename))
InvalidManifestError: 
=====> /home/evalverde/.cache/pre-commit/repoTO4tFY/.pre-commit-hooks.yaml does not exist

```

**Comment by asottile** [comment]
@khru please read above

**Comment by henryjiang-sfgov** [comment]
pre-commit autoupdate did not resolved the error. In fact, running pre-commit autoupdate throws the same error.

**Comment by asottile** [comment]
That likely means that the latest version of that repository  *also* doesn't have a `.pre-commit-hooks.yaml`, though without knowing the actual repo it's difficult to tell (looks like a private one?)

If you have commit access to that repo, you can usually `cp hooks.yaml .pre-commit-hooks.yaml`, assuming that file also exists.

You may also need to use `pre-commit autoupdate --bleeding-edge git@github.com:...` if the latest tagged revision in that repository doesn't contain a `.pre-commit-hooks.yaml`

**Comment by henryjiang-sfgov** [comment]
Thanks for the quick reply.  Yes it's a private repo and I'm trying to setup pre-commit for this repo. So 
I installed precommit using curl
start a new local branch
add the .pre-commit-config.yaml file
updated a readme.  
git add and commit
got the error

precommit config:
exclude: '^$'
fail_fast: false
repos:
  - repo: git@github.com:myrepo/myrepo.git
    rev: head 
    hooks:
      - id: forbid-binary

Btw, I'm running version 1.14.4 if that makes a difference. 
C02VCA2RHTD6:src henryjiang$ pre-commit --version
pre-commit 1.14.4

**Comment by asottile** [comment]
that all looks good, though you generally want to [avoid `head` as a `rev`](https://pre-commit.com/#using-the-latest-version-for-a-repository)

You'll need to make sure that the remote repository `myrepo/myrepo` has a `.pre-commit-hooks.yaml` with the [proper metadata](https://pre-commit.com/#new-hooks) in a `.pre-commit-hooks.yaml`

The subtlety is:
- *consuming* repos: `.pre-commit-config.yaml`
- *producing* repos: `.pre-commit-hooks.yaml`

**Comment by henryjiang-sfgov** [comment]
Here's what I end up doing:

- uninstall precommit
- add .pre-commit-hooks.yaml to my branch
- git commit
- install precommit
- get the revision from my last commit
- add .pre-commit-config.yaml
 
My branch is now clear to commit without error.  If using head is not recommended for the "rev" key in the config, does that mean we would have to keep updating that value for every commit? I must be missing something here.

**Comment by asottile** [comment]
Oh, you're trying to use a hook directly from the repository you're committing to instead of a remote repo, you probably want a [`local`](https://pre-commit.com/#repository-local-hooks) hook?

**Comment by henryjiang-sfgov** [comment]
Thanks! If I setup local hooks, are there still reasons to have precommit on my remote repo? The reason we want to use precommit is to enforce formatting and making sure we're not checking in passwords. 

TIA for your help.

**Comment by asottile** [comment]
Checking in `.pre-commit-config.yaml` is suggested.  The "remote" repositories are if you want to share that hook definition with multiple consuming repositories

**Comment by anentropic** [comment]
I think the part that is maybe not clear is the docs say:
> As long as your git repo is an installable package (gem, npm, pypi, etc.) or exposes an executable, it can be used with pre-commit.

But they also say:
> A git repo containing pre-commit plugins must contain a .pre-commit-hooks.yaml file

So this error means that one of the commands I'm trying to use as a pre-commit hook does not have a `.pre-commit-hooks.yaml` in its repo, _not_ that my project is missing that file.

The error would be more helpful if it specified which of the hooks caused it to be raised.

I don't really understand why it's not possible to specify entrypoint and args etc entirely on the user side? Unless I am missing something, to use some code I don't own as a pre-commit hook I have to make a 'wrapper' repo which installs it and provides a `.pre-commit-hooks.yaml` file?

I get that it's useful as a plugin author to be able to provide sensible defaults via the hooks yaml. But it would also be useful to be able to use arbitrary packages as pre-commit hooks by specifying all params as a user in `.pre-commit-config.yaml` just in the project where you want the hooks to run.

**Comment by anentropic** [comment]
never mind, I just found https://pre-commit.com/#repository-local-hooks

**Comment by anentropic** [comment]
TBH `local` hooks are not as good as `repo` hooks, you have to install the 'local' tool manually in advance of running `pre-commit install-hooks`  ... it seems a bit lame when the tool you want to use could easily be auto-installed by pre-commit

Have opened #1095

**Comment by asottile** [comment]
You don't need to preinstall, look at the `scss-lint` example in the linked docs

**Comment by amr1ta** [comment]
Here's what worked for me.
Suppose the error is:

```
An error has occurred: InvalidManifestError:
=====> /root/.cache/pre-commit/repo_MG9Ag/.pre-commit-hooks.yaml does not exist

```

To fix, simply run
```
mv /root/.cache/pre-commit/repo_MG9Ag/hooks.yaml /root/.cache/pre-commit/repo_MG9Ag/.pre-commit-hooks.yaml
```

**Comment by asottile** [comment]
@amr1ta that's not a good fix as the actual repository is **broken**, the actual repository should be fixed instead (often `pre-commit autoupdate` resolves this)
